<?php

/******************************************************************
 * Drupal Hooks
 *****************************************************************/


/**
 * Implements hook_form_alter
 */
function hc_hosting_form_alter(&$form, &$form_state, $form_id) {
  
  if (strstr($form_id, 'commerce_cart_add_to_cart_form')) {

  	$product_id = isset($form['product_id']['#value']) ? $form['product_id']['#value'] : $form['product_id']['#default_value'];

  	// get nid from product id
  	$product_fields = entity_metadata_wrapper('commerce_product', $product_id);

    // only for team package products
    if ($product_fields->type->value() == 'team_package') {

      $package_type = $product_fields->field_package_type->value();
    
      /* Package type = a taxonomy term object, so define a new wrapper for getting the info */
      $term = entity_metadata_wrapper('taxonomy_term', $package_type);
  
      $term_allow_hosting = (isset($term->field_allow_hosting)) ? $term->field_allow_hosting->value() : '0';
    
      if ($term_allow_hosting != 1) {
         unset($form['line_item_fields']['field_course_line_item_hosting']);
      }
      
    }
    
    // extra submit handler
    $form['#submit'][] = '_hc_hosting_form_submit';
    
    
  }
  
}


/**
 * Helper submit function
 */
function _hc_hosting_form_submit(&$form, &$form_state) {
  
  $values = $form_state['values'];
  $type = $form_state['default_product']->type;
  if ($type != "team_package") {
    return;
  }

  $line_item = $form_state['line_item'];
  
  if (!isset($values['line_item_fields']['field_course_line_item_hosting'])) {
    $line_item = entity_metadata_wrapper('commerce_line_item', $line_item);
      
  	$line_item->field_course_line_item_hosting->set('');
  	$line_item->save();
  }
}